obj-$(CONFIG_TOUCHSCREEN_GSL5680)    +=  gsl_point_id.o
$(obj)/gsl_point_id.o: $(srctree)/$(obj)/gsl_point_id 
	cp $(srctree)/$(obj)/gsl_point_id $(obj)/gsl_point_id.o
obj-$(CONFIG_TOUCHSCREEN_GSL5680)    +=  gsl_ts_driver.o
obj-$(CONFIG_TOUCHSCREEN_GSL5680)    +=  gsl_ts_test.o
